apiVersion: v1
kind: Secret
metadata:
  labels:
    testing.upbound.io/example-name: example_dcs_password
  name: example-dcs-password
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: SuperS3cr3tP4ssw0rd
